export const CURRENCIES = [
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'USD', symbol: '$', name: 'Dollar américain' },
  { code: 'GBP', symbol: '£', name: 'Livre sterling' },
  { code: 'JPY', symbol: '¥', name: 'Yen japonais' },
  { code: 'CHF', symbol: 'CHF', name: 'Franc suisse' },
  { code: 'CAD', symbol: 'CA$', name: 'Dollar canadien' },
  { code: 'AUD', symbol: 'A$', name: 'Dollar australien' },
  { code: 'CNY', symbol: '¥', name: 'Yuan chinois' },
  { code: 'INR', symbol: '₹', name: 'Roupie indienne' },
  { code: 'BRL', symbol: 'R$', name: 'Réal brésilien' },
  { code: 'RUB', symbol: '₽', name: 'Rouble russe' },
  { code: 'KRW', symbol: '₩', name: 'Won sud-coréen' },
  { code: 'MXN', symbol: 'MX$', name: 'Peso mexicain' },
  { code: 'IDR', symbol: 'Rp', name: 'Roupie indonésienne' },
  { code: 'TRY', symbol: '₺', name: 'Livre turque' },
  { code: 'SAR', symbol: '﷼', name: 'Riyal saoudien' },
  { code: 'SEK', symbol: 'kr', name: 'Couronne suédoise' },
  { code: 'NOK', symbol: 'kr', name: 'Couronne norvégienne' },
  { code: 'DKK', symbol: 'kr', name: 'Couronne danoise' },
  { code: 'PLN', symbol: 'zł', name: 'Złoty polonais' },
  { code: 'ZAR', symbol: 'R', name: 'Rand sud-africain' },
  { code: 'THB', symbol: '฿', name: 'Baht thaïlandais' },
  { code: 'HKD', symbol: 'HK$', name: 'Dollar de Hong Kong' },
  { code: 'SGD', symbol: 'S$', name: 'Dollar de Singapour' },
  { code: 'NZD', symbol: 'NZ$', name: 'Dollar néo-zélandais' },
  { code: 'ILS', symbol: '₪', name: 'Shekel israélien' },
  { code: 'PHP', symbol: '₱', name: 'Peso philippin' },
  { code: 'CZK', symbol: 'Kč', name: 'Couronne tchèque' },
  { code: 'HUF', symbol: 'Ft', name: 'Forint hongrois' },
  { code: 'MYR', symbol: 'RM', name: 'Ringgit malaisien' },
  { code: 'BGN', symbol: 'лв', name: 'Lev bulgare' },
  { code: 'RON', symbol: 'lei', name: 'Leu roumain' },
  { code: 'VND', symbol: '₫', name: 'Dong vietnamien' },
  { code: 'ARS', symbol: '$', name: 'Peso argentin' },
  { code: 'CLP', symbol: '$', name: 'Peso chilien' },
  { code: 'COP', symbol: '$', name: 'Peso colombien' },
  { code: 'EGP', symbol: '£', name: 'Livre égyptienne' },
  { code: 'MAD', symbol: 'DH', name: 'Dirham marocain' },
  { code: 'TND', symbol: 'DT', name: 'Dinar tunisien' },
  { code: 'DZD', symbol: 'DA', name: 'Dinar algérien' },
  { code: 'XOF', symbol: 'CFA', name: 'Franc CFA (BCEAO)' },
  { code: 'XAF', symbol: 'CFA', name: 'Franc CFA (BEAC)' },
  { code: 'NGN', symbol: '₦', name: 'Naira nigérian' },
  { code: 'KES', symbol: 'KSh', name: 'Shilling kényan' },
  { code: 'GHS', symbol: 'GH₵', name: 'Cedi ghanéen' },
  { code: 'AED', symbol: 'dh', name: 'Dirham des Émirats' },
  { code: 'UAH', symbol: '₴', name: 'Hryvnia ukrainienne' },
];

export const getCurrencySymbol = (code: string) => {
  const currency = CURRENCIES.find(c => c.code === code);
  return currency ? currency.symbol : code;
};